#!/bin/bash
C=/${0}
C=${C%/*}
if test -e /System/Library/Frameworks/GameController.framework; then
	exec "${C:-.}"/CocoaTop
elif test -e /System/Library/Frameworks/MediaToolbox.framework; then
	exec "${C:-.}"/CocoaTop6
else
	exec "${C:-.}"/CocoaTop5
fi